"""Regenerate server/pyta_lsp/pyta_codes.py from the PythonTA checkers page.

The page marks every documented message with an anchor id equal to the
lowercased message id (e.g. id="e9989").
"""
from __future__ import annotations

import re
import sys
import urllib.request
from pathlib import Path

PAGE = "https://www.cs.toronto.edu/~david/pyta/checkers/index.html"
OUT = Path(__file__).resolve().parents[1] / "server" / "pyta_lsp" / "pyta_codes.py"
ANCHOR = re.compile(r'id="([a-z][0-9]{4})"')


def main() -> int:
    with urllib.request.urlopen(PAGE, timeout=30) as resp:
        html = resp.read().decode("utf-8", errors="replace")
    codes = sorted({m.upper() for m in ANCHOR.findall(html)})
    if len(codes) < 100:
        print(f"only found {len(codes)} codes; page layout may have changed", file=sys.stderr)
        return 1
    body = ",\n".join(f'    "{code}"' for code in codes)
    OUT.write_text(
        '"""Message codes documented on the PythonTA checkers page. Generated by scripts/gen_pyta_codes.py."""\n'
        "PYTA_DOCUMENTED_CODES: frozenset[str] = frozenset([\n"
        f"{body},\n"
        "])\n",
        encoding="utf-8",
    )
    print(f"wrote {len(codes)} codes to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
